version: "3"
services:
  complexity_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: complexity_app
    env_file:
      - complexity_app/.env
    networks:
      - default
    ports:
      - "8000:8000"

volumes:
    data:
      driver: local
