version: "3"
services:
  keydb:
    container_name: keydb
    image: eqalpha/keydb:latest
    command: keydb-server /etc/keydb/keydb.conf --server-threads 2  --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - default
    volumes:
      - data:/data
    ports:
      - "6379:6379"

  kdb-panel:
    container_name: kdb-panel
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      REDIS_HOST: keydb
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "8081:8081"

  complexity_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: complexity_app
    env_file:
      - complexity_app/.env
    networks:
      - default
    depends_on:
      - keydb
    ports:
      - "8000:8000"

volumes:
    data:
      driver: local
